// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type RequestBlob struct {
	Name        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	RequestJson interface{}
}
