// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Request struct {
	ID          string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Name        string
	Method      string
	Url         string
	ContentType sql.NullString
	Body        sql.NullString
	Params      sql.NullString
	Auth        sql.NullString
	Headers     sql.NullString
}
