// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package database

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
  id, name, method, url, content_type, body, params, auth, headers
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, created_at, updated_at, name, method, url, content_type, body, params, auth, headers
`

type CreateRequestParams struct {
	ID          string
	Name        string
	Method      string
	Url         string
	ContentType sql.NullString
	Body        sql.NullString
	Params      sql.NullString
	Auth        sql.NullString
	Headers     sql.NullString
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.ID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.ContentType,
		arg.Body,
		arg.Params,
		arg.Auth,
		arg.Headers,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.ContentType,
		&i.Body,
		&i.Params,
		&i.Auth,
		&i.Headers,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, id)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT id, created_at, updated_at, name, method, url, content_type, body, params, auth, headers FROM requests WHERE id = ? LIMIT 1
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.ContentType,
		&i.Body,
		&i.Params,
		&i.Auth,
		&i.Headers,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, created_at, updated_at, name, method, url, content_type, body, params, auth, headers FROM requests ORDER BY created_at DESC
`

func (q *Queries) ListRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.ContentType,
			&i.Body,
			&i.Params,
			&i.Auth,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByMethod = `-- name: ListRequestsByMethod :many
SELECT id, created_at, updated_at, name, method, url, content_type, body, params, auth, headers FROM requests WHERE method = ? ORDER BY created_at DESC
`

func (q *Queries) ListRequestsByMethod(ctx context.Context, method string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByMethod, method)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.ContentType,
			&i.Body,
			&i.Params,
			&i.Auth,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests
SET name = ?, method = ?, url = ?, content_type = ?, body = ?,
    params = ?, auth = ?, headers = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, created_at, updated_at, name, method, url, content_type, body, params, auth, headers
`

type UpdateRequestParams struct {
	Name        string
	Method      string
	Url         string
	ContentType sql.NullString
	Body        sql.NullString
	Params      sql.NullString
	Auth        sql.NullString
	Headers     sql.NullString
	ID          string
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, updateRequest,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.ContentType,
		arg.Body,
		arg.Params,
		arg.Auth,
		arg.Headers,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.ContentType,
		&i.Body,
		&i.Params,
		&i.Auth,
		&i.Headers,
	)
	return i, err
}
