// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package database

import (
	"context"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO request_blobs (
  name, request_json
) VALUES (
    ?, ?
)
RETURNING name, created_at, updated_at, request_json
`

type CreateRequestParams struct {
	Name        string
	RequestJson interface{}
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (RequestBlob, error) {
	row := q.db.QueryRowContext(ctx, createRequest, arg.Name, arg.RequestJson)
	var i RequestBlob
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestJson,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM request_blobs WHERE name = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, name)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT name, created_at, updated_at, request_json FROM request_blobs WHERE name = ? LIMIT 1
`

func (q *Queries) GetRequest(ctx context.Context, name string) (RequestBlob, error) {
	row := q.db.QueryRowContext(ctx, getRequest, name)
	var i RequestBlob
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestJson,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT name, created_at, updated_at, request_json FROM request_blobs ORDER BY created_at DESC
`

func (q *Queries) ListRequests(ctx context.Context) ([]RequestBlob, error) {
	rows, err := q.db.QueryContext(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestBlob
	for rows.Next() {
		var i RequestBlob
		if err := rows.Scan(
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE request_blobs
SET request_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE name = ?
RETURNING name, created_at, updated_at, request_json
`

type UpdateRequestParams struct {
	RequestJson interface{}
	Name        string
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (RequestBlob, error) {
	row := q.db.QueryRowContext(ctx, updateRequest, arg.RequestJson, arg.Name)
	var i RequestBlob
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestJson,
	)
	return i, err
}
