version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.25'

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - staticcheck
